### ISSUE TITLE
[3.1] Table Generation Documentation

### ISSUE THREAD

**Issue by stevebauman** [orchestral/html#35]
I know you have an entire awesome platform to worry about, but I'm just trying to work through generating tables without documentation and can't seem to get it going. Is there any chance you could show a small snippet of code for generating a table whenever you have a minute?

Thanks for your awesome work!

**Comment by crynobone** [comment]
To begin with, here's the most basic example:

```php
use App\User;
use Orchestra\Support\Facades\Table;

$user = User::query();

$table = Table::of('users.list', function ($table) use ($model) {
     $table->with($model); // this automatically handle pagination.

     $table->sortable(); // allow sorting, e.g: ?order_by=username&direction=desc etc

     $table->column('id', 'ID');
     $table->column('fullname')->label('Full Name')->value(function ($user) {
          return $user->first_name.' '.$user->last_name;
     });
});
```

**Comment by crynobone** [comment]
There many related example available from <https://github.com/orchestral/foundation/blob/master/src/Http/Presenters/> as well.

**Comment by stevebauman** [comment]
This is great, thanks a ton for the quick response!
