### ISSUE TITLE
[5.1] __toString() Exception when using outside of Foundation

### ISSUE THREAD

**Issue by stevebauman** [orchestral/html#36]
When calling `$control->getField($row, $control, [])` this generates an exception when using the package outside of foundation.

https://github.com/orchestral/html/blob/master/src/Form/Fieldset.php#L71

**Comment by crynobone** [comment]
Is this still an issue after orchestral/html@250cc2c?

**Comment by stevebauman** [comment]
Nope this isn't an issue anymore! Thanks! :+1:
