### ISSUE TITLE
Sorting by an non-existent column causes exception

### ISSUE THREAD

**Issue by stevebauman** [orchestral/html#39]
Calling sortable on a `TableGrid` instance, then entering in a url such as `admin/users?order_by=test` causes `PDOException`

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'test' in 'order clause'
```

Maybe we could just check if the column exists in the models database table before trying to run the `orderBy()` method? Or maybe check if the column exists as an attribute in the model?

**Comment by crynobone** [comment]
A simple solution is to just the first parameter.

```
$table->sortable(['only' => ['username', 'email']);
```

Checking if the column exists in the models would be possible, but we also support basic fluent query, can we handle both scenario? If so, it should be done in <https://github.com/orchestral/support/blob/master/src/Support/Traits/QueryFilterTrait.php#L16>

**Comment by stevebauman** [comment]
Oh is that already implemented? Also this exception occurs in foundation as well if you go to the administrator panel and enter a non-existent column in the query parameter for `order_by`

**Comment by crynobone** [comment]
```php
$table->sortable(['only' => ['username', 'email']);
```

This should be the way to go.
