### ISSUE TITLE
[3.1] Altering the submit button on forms

### ISSUE THREAD

**Issue by stevebauman** [orchestral/html#42]
I'm not sure if it's possible, but I've been trying to alter the submit button on forms and haven't been able to get it. Is there currently a way of doing this? I just need to add attributes to it for styling and other purposes.

Thanks!

**Comment by crynobone** [comment]
```
Form::of('users', function ($form) {
    $form->submit = "New button"; 
});
```

This should work, AFAIK.

**Comment by stevebauman** [comment]
Ok great, is there a way of altering the style or add attributes to the submit button as well?

**Comment by crynobone** [comment]
Not straightforward. You need to pass in a renderable object and tweak the template.

```php
class SubmitButton {
    // ...
    public function render() {

    } 
}
```

```html
<div> ....
    {!! $submit->render() !!}
</div>
```

**Comment by stevebauman** [comment]
Ah that's perfect, thanks again!

Orchestra just keeps getting better and better
